version: "3.9"

services:
    expo:
        container_name: steady_expo
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: development
        ports:
            - "19000:19000" # Metro bundler (iOS/Android)
            - "19001:19001" # Expo DevTools
            - "19002:19002" # Web preview
        volumes:
            - .:/app
            - /app/node_modules # Keeps local node_modules from conflicting
            - sqlite_data:/app/data # Persist SQLite data
        environment:
            - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
            - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
            - NODE_ENV=development
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:19000"]
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
        command: ["npx", "expo", "start", "--clear"]

volumes:
    sqlite_data: # Named volume for SQLite data persistence
