version: "3.9"

services:
    expo:
        container_name: steady_expo
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "19000:19000" # Metro bundler (iOS/Android)
            - "19001:19001" # Expo DevTools
            - "19002:19002" # Web preview
        volumes:
            - .:/app
            - /app/node_modules # Keeps local node_modules from conflicting
        environment:
            - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
            - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
        command: ["npx", "expo", "start", "-c"]
